# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

def default_zalando_pods 
 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'

end

target 'ZalandoAPPDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZalandoAPPDemo
   
  default_zalando_pods

  target 'ZalandoAPPDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZalandoAPPDemoUITests' do
    # Pods for testing
  end

end

target 'ZalandoAPPDemoDev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  default_zalando_pods
  # Pods for ZalandoAPPDemoDev

end
